# Generated by Django 6.0.4 on 2026-04-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
    ]
