# Generated by Django 6.0.4 on 2026-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="E-mail d'échec envoyé le"),
        ),
    ]
