# Generated by Django 6.0.4 on 2026-09-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_normalize_user_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_hash', max_length=128, verbose_name='password'),
        ),
    ]
