# Generated by Django 6.0.4 on 2026-04-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
    ]
