# Generated by Django 6.0.4 on 2026-04-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('category', models.CharField(choices=[('ANNIVERSAIRE', 'Anniversaire'), ('MARIAGE', 'Mariage'), ('SEMINAIRE', 'Séminaire'), ('ECOLE', 'École'), ('AUTRE', 'Autre')], default='ANNIVERSAIRE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_children', models.PositiveIntegerField(default=15)),
                ('min_children', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_type', models.CharField(choices=[('FIXED', 'Prix Fixe'), ('PER_CHILD', 'Par Enfant'), ('PER_HOUR', 'Par Heure')], default='FIXED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services.service')),
            ],
        ),
    ]
