# Generated by Django 6.0.4 on 2026-09-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_option_options_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image ou icône de l'option", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='badge_label',
            field=models.CharField(blank=True, help_text="Badge promotionnel (ex: 'Top Ventes', 'Coup de Cœur')", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL de l'image de couverture HD", max_length=500, null=True),
        ),
    ]
