# Generated by Django 6.0.4 on 2026-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_option_image_url_service_badge_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_column='title', max_length=200),
        ),
    ]
