"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-==8d!h#agw5o+el=tn5pll_wq25iem5^=shylk8xpnb8#7c%j*')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] if DEBUG else os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    # Local apps
    'core',
    'users',
    'services',
    'bookings',
    'payments',
    'availability',
    'media',
    'contact',
    'reviews',
    'drf_spectacular',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth settings
AUTH_USER_MODEL = 'users.User'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/auth/login/'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

# Simple JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True # Change in production
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Funkidz API',
    'DESCRIPTION': 'API pour la plateforme de réservation d\'animations Funkidz',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Funkidz Admin",
    "site_header": "Funkidz",
    "site_brand": "Funkidz Admin",
    "welcome_sign": "Bienvenue sur l'Espace de Gestion Funkidz",
    "copyright": "Funkidz Animation",
    "search_model": ["users.User", "bookings.Booking", "services.Service"],
    "topmenu_links": [
        {"name": "Tableau de Bord", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Voir le Site Public 🌐", "url": "/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "users.User": "fas fa-users-cog",
        "users.AnimateurProfile": "fas fa-user-ninja",
        "services.Service": "fas fa-magic",
        "services.Option": "fas fa-tags",
        "bookings.Booking": "fas fa-calendar-check",
        "bookings.BookingAssignment": "fas fa-user-check",
        "bookings.BookingOption": "fas fa-list-ul",
        "payments.Payment": "fas fa-credit-card",
        "availability.Availability": "fas fa-calendar-times",
        "availability.WeeklySchedule": "fas fa-clock",
        "availability.AnimateurLeave": "fas fa-plane-departure",
        "contact.ContactMessage": "fas fa-envelope-open-text",
        "media.MediaGallery": "fas fa-images",
        "reviews.Review": "fas fa-star",
    },
    "order_with_respect_to": ["users", "services", "bookings", "payments", "availability", "contact"],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-white",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# ==========================================
# EMAIL CONFIGURATION (SMTP RÉEL / BREVO / LOCALHOST)
# ==========================================
_email_backend_env = os.getenv('EMAIL_BACKEND')
if _email_backend_env:
    EMAIL_BACKEND = _email_backend_env
elif os.getenv('EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))

# Dossier de dépôt des e-mails quand EMAIL_BACKEND est le backend "filebased"
# (utile pour une démonstration : chaque e-mail est écrit dans un fichier lisible).
EMAIL_FILE_PATH = os.getenv('EMAIL_FILE_PATH', str(BASE_DIR / 'sent_emails'))

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Funkidz Animation <contact@funkidz.fr>')

# Destinataires des notifications administratives.
# Renseigner ADMIN_NOTIFICATION_EMAILS dans le .env (adresses séparées par des
# virgules) pour router explicitement les e-mails admin vers une boîte de test.
# Si la variable est vide, les destinataires sont déduits des comptes
# administrateurs enregistrés (voir core.utils.get_admin_recipient_emails).
ADMIN_NOTIFICATION_EMAILS = [
    addr.strip()
    for addr in os.getenv('ADMIN_NOTIFICATION_EMAILS', '').split(',')
    if addr.strip() and '@' in addr
]
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')

# ==========================================
# STRIPE CONFIGURATION
# ==========================================
STRIPE_API_KEY = os.getenv('STRIPE_API_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')


def _stripe_key_is_usable(key):
    """Une clé Stripe exploitable commence par sk_/pk_ et n'est pas un placeholder."""
    if not key or 'REMPLACER' in key:
        return False
    return key.startswith(('sk_', 'pk_', 'rk_'))


# Vrai uniquement si les deux clés Stripe nécessaires au formulaire de carte
# (clé secrète côté serveur, clé publiable côté navigateur) sont renseignées.
STRIPE_ENABLED = _stripe_key_is_usable(STRIPE_API_KEY) and _stripe_key_is_usable(STRIPE_PUBLISHABLE_KEY)

