# Generated by Django 6.0.4 on 2026-04-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.animateurprofile')),
            ],
        ),
    ]
