# Generated by Django 6.0.4 on 2026-04-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Disponibilité', 'verbose_name_plural': 'Disponibilités'},
        ),
    ]
