# Generated by Django 6.0.4 on 2026-05-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_alter_availability_options'),
        ('users', '0002_alter_animateurprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimateurLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='users.animateurprofile')),
            ],
            options={
                'verbose_name': 'Congé Animateur',
                'verbose_name_plural': 'Congés Animateurs',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='users.animateurprofile')),
            ],
            options={
                'verbose_name': 'Horaire Récurrent',
                'verbose_name_plural': 'Horaires Récurrents',
                'unique_together': {('animateur', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
