# Generated by Django 6.0.4 on 2026-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_animateurleave_weeklyschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], db_column='day_of_week'),
        ),
    ]
