# Generated by Django 6.0.4 on 2026-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'verbose_name': 'Élément multimédia', 'verbose_name_plural': 'Galerie multimédia'},
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='file',
            field=models.FileField(blank=True, help_text='Importer depuis votre ordinateur', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='mediagallery',
            name='media_url',
            field=models.URLField(blank=True, help_text='Lien externe (ex: YouTube)'),
        ),
    ]
