# Generated by Django 6.0.4 on 2026-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_mediagallery_options_mediagallery_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], db_column='type', default='IMAGE', max_length=10),
        ),
    ]
