# Generated by Django 6.0.4 on 2026-09-28 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_mediagallery_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediagallery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
