# Generated by Django 6.0.4 on 2026-04-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-booking_time'], 'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='bookingassignment',
            options={'verbose_name': "Assignation d'animateur", 'verbose_name_plural': "Assignations d'animateurs"},
        ),
        migrations.AlterModelOptions(
            name='bookingoption',
            options={'verbose_name': 'Option de réservation', 'verbose_name_plural': 'Options de réservation'},
        ),
    ]
