# Generated by Django 6.0.4 on 2026-09-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='child_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge fêté'),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Prénom de l'enfant"),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone de contact'),
        ),
    ]
