# Generated by Django 6.0.4 on 2026-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_child_age_booking_child_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notification admin envoyée le'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="E-mail d'annulation envoyé le"),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-mail de confirmation client envoyé le'),
        ),
        migrations.AddField(
            model_name='bookingassignment',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notification animateur envoyée le'),
        ),
    ]
