# Generated by Django 6.0.4 on 2026-09-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_admin_notification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('CLIENT', 'Client')], default='', max_length=10, verbose_name='Annulée par'),
        ),
    ]
