# Generated by Django 6.0.4 on 2026-09-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_cancelled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(db_column='event_date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(db_column='start_time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_address',
            field=models.CharField(db_column='address', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location_city',
            field=models.CharField(db_column='city', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nb_children',
            field=models.PositiveIntegerField(db_column='children_count'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True, db_column='notes'),
        ),
        migrations.AlterField(
            model_name='bookingoption',
            name='price_at_time',
            field=models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10),
        ),
    ]
