# Generated by Django 6.0.4 on 2026-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_id_alter_bookingassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', verbose_name="Motif de l'annulation"),
        ),
        migrations.AddField(
            model_name='bookingassignment',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Réponse de l'animateur le"),
        ),
        migrations.AlterField(
            model_name='bookingassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='assigned_at'),
        ),
    ]
